providers:
  - name: RIOSUCIO-CPRSUMPSER-264913
    local_address: 10.8.8.1
    wan: sfp-sfpplus1
    saturation: 3200000000
  - name: SUPIA-CPSUIIDSER-272906
    local_address: 10.9.9.1
    wan: sfp-sfpplus2
    saturation: 1000000000