providers:
  - name: UNE_1G_SER_244912
    local_address: 10.8.8.10
    wan: ether1
    saturation: 950000000
  - name: LUMEN_RIOSUCIO_2G_ID:81-1V9YEMV
    local_address: 10.8.8.6
    wan: sfp-sfpplus1
    saturation: 1950000000
  - name: LUMEN_SUPIA_1G_ID:81-2V79WV3
    local_address: 172.16.201.158
    wan: sfp-sfpplus1
    saturation: 950000000